name: Run Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run_unit_tests:
    name: Build & Run Unit Tests
    runs-on: ubuntu-latest
  
    steps:
    - name: Setup Repository
      uses: ./.github/workflows/setup_repository.yaml

    - name: Compile Unit Tests
      run: make
      working-directory: Code/unittest
    
    - name: Run Unit Tests
      run: make run
      working-directory: Code/unittest
  
  run_component_tests:
    name: Build Evaluation & Run Component Tests
    runs-on: ubuntu-latest

    steps:
    - name: Setup Repository
      uses: ./.github/workflows/setup_repository.yaml

    - name: Compile Evaluation Component
      run: make
      working-directory: Code/evaluation

    - name: Run Component Tests
      run: pytest
      working-directory: Code/componenttest
