name: Setup Repository

on:
  workflow_call:

jobs:
  setup_repository:
    name: Set Up Machine & Repository
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Run Setup Script
      run: ./setup_repo.sh
      working-directory: Code